### PR TITLE
Add design prototype

### LINKED ISSUE #8: As a developer, I want to have a design prototype so I can create the website.
Inspiration: https://preview.themeforest.net/item/zuhaus-a-modern-real-estate-and-rental-theme/full_screen_preview/21023761?_ga=2.56818282.1779188942.1576049954-2084714641.1569260807

### PR DESCRIPTION
**Pull request by lmachens**
closes #8

### CODE REVIEW

**Review by holgermanzke — COMMENTED** [review]
LGTM

**Review by marwinburesch — APPROVED** [review]
very nice work

**Review by marvingradtke — APPROVED** [review]
LGTM

**Review by franzosterkamp — CHANGES_REQUESTED** [review]
looks ugly!

**Review by tobiaserich — CHANGES_REQUESTED** [review]
what are you doing?!?!

**Pull request merged**
